project:
  type: website
  output-dir: docs

website:
  title: "Sanjeeva Reddy Dodlapati"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      dark: slate
      light: minty
    css: styles.css
    toc: true



image: Profile.jpeg
about: 
  template: trestles
  image-shape: rounded
  image-width: 15em
  links:
    - text: LinkedIn
      href: https://www.linkedin.com/in/sanjeeva-reddy-dodlapati-ab4ab490/
    - text: Twitter
      href: https://twitter.com/dodlapati_reddy
    - text: GitHub
      href: https://github.com/SanjeevaRDodlapati
    - text: sdodl001@odu.edu
      href: mailto:sdodl001@odu.edu