
project:
  type: website
  output-dir: docs

website:
  title: "AI for Science Blog"
  navbar:
    left:
      - href: index.html
        text: About
      # - href: about.html
        # text: Research Interests
      - href: ml-blog.html
        text: Machine Learning
      - href: genomics-blog.html
        text: AI for Genomics
      - href: blog.html
        text: Bioinformatics


format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: false

      