
project:
  type: website
  output-dir: docs

website:
  title: "Sanjeev's AI Research Blog"
  description: "Advanced AI research, computational biology, and data science insights"
  navbar:
    background: light
    style: floating
    left:
      - href: index.html
        text: About
        icon: person-circle
      - href: ml-blog.html
        text: Machine Learning
        icon: cpu
      - href: genomics-blog.html
        text: AI for Genomics
        icon: dna
      - href: chemistry-blog.html
        text: AI for Chemistry
        icon: flask
    right:
      - icon: github
        href: https://github.com/SanjeevaRDodlapati
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/dodlapati_reddy
        aria-label: Twitter
    tools:
      - icon: moon
        href: "#"
        text: "Toggle Dark Mode"
        toggle: dark
  
  page-footer:
    background: light
    left: |
      © 2025 Sanjeeva Reddy Dodlapati  
      AI Research • Computational Biology • Data Science
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/sanjeeva-reddy-dodlapati-ab4ab490/
        aria-label: LinkedIn
      - icon: envelope
        href: mailto:sdodlapa@gmail.com
        aria-label: Email

format:
  html:
    theme:
      - cosmo
      - modern-professional-theme.scss
    css: styles.css
    toc: true
    toc-depth: 3
    code-copy: hover
    code-overflow: wrap
    highlight-style: github-dark
    anchor-sections: true
    smooth-scroll: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    include-in-header:
      - text: |
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <meta name="author" content="Sanjeeva Reddy Dodlapati">
          <meta name="keywords" content="AI, machine learning, computational biology, bioinformatics, genomics, data science">
          <script src="custom.js" defer></script>
          <style>
            body { opacity: 0; transition: opacity 0.3s ease; }
            body.loaded { opacity: 1; }
          </style>
    lang: en