---
title: "Home"
sidebar: home-sidebar
---

# Welcome to My Website

Welcome to my personal website. Here, you'll find information about my research interests, blog posts, and more.



------------------------------------------------------------------------

## Education

-   PhD in Computer Science, Old Dominion University, Norfolk, VA, 23508
-   MS Chemistry, University of New Orleans, LA

------------------------------------------------------------------------

## Experience

### Research

-   Intern, BI, CT Jun 2018 - Aug 2018
-   Project Lead, Indian Institute of Chemical Technology, Hyderabad.

### Teaching

-   Teaching Assistant, Department of Computer Science, ODU, Norfolk, VA, 23508

------------------------------------------------------------------------

## Projects

-   DNA methylation imputation via Transfer Learning.
-   Sample complexity study of DNA methylation prediction by DNA sequence-based deep learning
-   Drug-Drug interaction prediction
-   Synthesis of macrocyclic glycosamines by click reaction

------------------------------------------------------------------------

## Publications

-   Sanjeeva Dodlapati, ZC Jiang, J Sun, [Completing Single-Cell DNA Methylome Profiles via Transfer Learning together with KL-Divergence.](https://www.frontiersin.org/articles/10.3389/fgene.2022.910439/full) Frotiers in Genetics 2022

-   [Loss of Acta2 in cardiac fibroblasts does not prevent the myofibroblast differentiation or affect the cardiac repair after myocardial infarction.](https://doi.org/10.1016/j.yjmcc.2022.08.003) Journal of Molecular and Cellular Cardiology 171, 117-132.

-   [The landscape of accessible chromatin in quiescent cardiac fibroblasts and cardiac fibroblasts activated after myocardial infarction.](https://doi.org/10.1080/15592294.2021.1982158). Epigenetics 2021.

------------------------------------------------------------------------
